name: Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      # Install root dependencies
      - name: Install Root Dependencies
        shell: bash
        run: bun install

      # Install Vercel CLI globally using bun
      - name: Install Vercel CLI
        shell: bash
        run: bun add -g vercel@latest

      # Run Vercel commands from the Astro directory
      - name: Pull Vercel Environment Information
        working-directory: ./apps/astro
        shell: bash
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        working-directory: ./apps/astro
        shell: bash
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        working-directory: ./apps/astro
        shell: bash
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
